# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Xilinx/Vivado/2017.4/data/boards/board_files/MiniZed_Constraints_Rev1_170613.xdc

# Block Designs: bd/Zynq_System/Zynq_System.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_System || ORIG_REF_NAME==Zynq_System} -quiet] -quiet

# IP: bd/Zynq_System/ip/Zynq_System_processing_system7_0_0/Zynq_System_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_System_processing_system7_0_0 || ORIG_REF_NAME==Zynq_System_processing_system7_0_0} -quiet] -quiet

# IP: bd/Zynq_System/ip/Zynq_System_proc_sys_reset_0_1/Zynq_System_proc_sys_reset_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_System_proc_sys_reset_0_1 || ORIG_REF_NAME==Zynq_System_proc_sys_reset_0_1} -quiet] -quiet

# IP: bd/Zynq_System/ip/Zynq_System_LogicSignalOut_0_0/Zynq_System_LogicSignalOut_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_System_LogicSignalOut_0_0 || ORIG_REF_NAME==Zynq_System_LogicSignalOut_0_0} -quiet] -quiet

# XDC: bd/Zynq_System/Zynq_System_ooc.xdc
