# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z007sclg225-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Users/Public/Zynq System/Zynq System.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Public/Zynq System/Zynq System.xpr} [current_project]
set_property XPM_LIBRARIES {XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:minized:part0:1.2 [current_project]
set_property ip_output_repo {c:/Users/Public/Zynq System/Zynq System.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {{C:/Users/Public/Zynq System/Zynq System.srcs/sources_1/bd/Zynq_System/hdl/Zynq_System_wrapper.v}}
add_files {{C:/Users/Public/Zynq System/Zynq System.srcs/sources_1/bd/Zynq_System/Zynq_System.bd}}
set_property used_in_implementation false [get_files -all {{c:/Users/Public/Zynq System/Zynq System.srcs/sources_1/bd/Zynq_System/ip/Zynq_System_processing_system7_0_0/Zynq_System_processing_system7_0_0.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Public/Zynq System/Zynq System.srcs/sources_1/bd/Zynq_System/ip/Zynq_System_proc_sys_reset_0_1/Zynq_System_proc_sys_reset_0_1_board.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Public/Zynq System/Zynq System.srcs/sources_1/bd/Zynq_System/ip/Zynq_System_proc_sys_reset_0_1/Zynq_System_proc_sys_reset_0_1.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Public/Zynq System/Zynq System.srcs/sources_1/bd/Zynq_System/ip/Zynq_System_proc_sys_reset_0_1/Zynq_System_proc_sys_reset_0_1_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{C:/Users/Public/Zynq System/Zynq System.srcs/sources_1/bd/Zynq_System/Zynq_System_ooc.xdc}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Xilinx/Vivado/2017.4/data/boards/board_files/MiniZed_Constraints_Rev1_170613.xdc
set_property used_in_implementation false [get_files C:/Xilinx/Vivado/2017.4/data/boards/board_files/MiniZed_Constraints_Rev1_170613.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top Zynq_System_wrapper -part xc7z007sclg225-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Zynq_System_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Zynq_System_wrapper_utilization_synth.rpt -pb Zynq_System_wrapper_utilization_synth.pb"
